export const queryKeys = {
  me: ["me"] as const,
  listings: (params?: Record<string, unknown>) => ["listings", params ?? {}] as const,
  listing: (idOrSlug: string) => ["listing", idOrSlug] as const,
  categories: ["categories"] as const,
  myBusinesses: ["businesses", "mine"] as const,
  business: (id: string) => ["business", id] as const,
  offers: ["offers"] as const,
  offer: (id: string) => ["offer", id] as const,
  watchlist: ["watchlist"] as const,
  savedSearches: ["saved-searches"] as const,
  conversations: ["conversations"] as const,
  messages: (conversationId: string) => ["conversation", conversationId, "messages"] as const,
  notifications: ["notifications"] as const,
  subscription: ["subscription"] as const,
  deals: ["deals"] as const,
  deal: (id: string) => ["deal", id] as const,
  dueDiligence: (dealId: string) => ["deal", dealId, "due-diligence"] as const,
  aiAnalysis: (businessId: string) => ["business", businessId, "ai-analysis"] as const,
  adminUsers: (cursor?: string) => ["admin", "users", cursor ?? null] as const,
  adminBusinesses: (status?: string, cursor?: string) => ["admin", "businesses", status ?? null, cursor ?? null] as const,
  adminVerifications: (cursor?: string) => ["admin", "verifications", cursor ?? null] as const,
  adminReports: (cursor?: string) => ["admin", "reports", cursor ?? null] as const,
  adminAuditLogs: (cursor?: string) => ["admin", "audit-logs", cursor ?? null] as const,
};
